### ISSUE TITLE
为什么没有代码的高亮样式

### ISSUE THREAD

**Issue by riba2534** [maicong/stay#1]
为什么没有代码的高亮样式?是我设置不对么

**Comment by maicong** [comment]
markdown 插入代码块并高亮，需要在 ``` 后面指定代码语言类型，比如高亮 javascript：

**不指定语言类型：**

&#x60;&#x60;&#x60;
var text = &#x27;hello&#x27;;
alert(text);
&#x60;&#x60;&#x60;

显示为： 

```
var text = 'hello';
alert(text);
```

**指定语言类型：**

&#x60;&#x60;&#x60;javascript
var text = &#x27;hello&#x27;;
alert(text);
&#x60;&#x60;&#x60;

显示为：

```javascript
var text = 'hello';
alert(text);
```

具体 markdown 语法请看：https://guides.github.com/features/mastering-markdown/

**Comment by maicong** [comment]
如果你没有开启 markdown 书写功能，高亮代码的话需要添加 `lang` 标签来指定代码语言，例如：

```html
<pre lang="javascript">
var text = 'hello';
alert(text);
</pre>
```
显示为：

<pre lang="javascript">
var text = 'hello';
alert(text);
</pre>

**Comment by riba2534** [comment]
是开了markdown功能的，开了以后标签里面写了cpp,c++都试过，结果是不显示代码高亮

**Comment by maicong** [comment]
主题默认的高亮类型是这几种：
```
markup、css、javascript、bash、git、ini、json、nginx、php、pug、sql、wiki
```
高亮代码文件为：

https://github.com/maicong/stay/blob/master/assets/src/js/lib/prism.js

要加入更多类型支持，请执行以下步骤：

1. 打开文件注释里的链接
2. 勾选你需要支持的类型
3. 点击 `Download JS`，保存这个文件
4. 用编辑器打开下载的 prism.js，将代码里的所有 `language-` 替换为 `lang-`
5. 覆盖主题里的 `assets/src/js/lib/prism.js` 文件
6. 进入 `assets` 目录，重新运行一次打包命令（[命令说明](https://github.com/maicong/stay/blob/master/assets/README.md#%E5%91%BD%E4%BB%A4%E8%AF%B4%E6%98%8E)）
7. 覆盖原始文件
